In [0]:
### Insertando código Python

In [1]:
x = 10
y = 15
prom = (x+y)/2
print (prom)

12.5


In [4]:
### Trabajando con listas
A = [5.2,5.8,5.9]
print(A)

[5.2, 5.8, 5.9]


In [5]:
s = 0
for i in A:
    s += i
print(s)    

16.9


In [26]:
###importando librerías:
import numpy as np
Ar = np.array(A)
print(Ar)
sum(Ar)
media = np.mean(Ar)
print(media)
varianza = np.var(Ar)
print(varianza)
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print(np.mean(B[0]))
print(np.mean(B,axis=1))
print(np.mean(B,axis=0))
print(B.mean(axis=1))
print(B.mean(axis=0))
print(B[:,0].mean())
print(B[:,1].mean())

[5.2 5.8 5.9]
5.633333333333333
0.09555555555555555
[[1 2]
 [3 4]
 [5 6]]
1.5
[1.5 3.5 5.5]
[3. 4.]
[1.5 3.5 5.5]
[3. 4.]
3.0
4.0


In [41]:
###Python permite ejecutar línea de comando directamente desde el notebook
!ls -l
!pwd

total 80
-rw-r--r-- 1 vana vana 79491 Aug 25 19:43 notebook1.ipynb


In [51]:
! pip install pandas
import pandas

In [81]:
! echo "hola mundo"
! mkdir PRUEBA
! ls -l
! pwd

hola mundo
total 72
-rw-r--r-- 1 vana vana 65740 Aug 25 20:25 notebook1.ipynb
drwxr-xr-x 2 vana vana  4096 Aug 25 20:25 PRUEBA
/home/vana/Desktop/notebooksJupyter
